// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bywrwdxfgjzxqnpoibrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5d3J3ZHhmZ2p6eHFucG9pYnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTEwODEsImV4cCI6MjA2NDc2NzA4MX0.1GC2dDLVsyEH09HWsZcBXfbN2NeuH0aRov11MbcUYSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);